### ISSUE TITLE
Clarifying status of RTC books whose covers are provided but which are not on spreadsheet

### ISSUE THREAD

**Issue by rdhyee** [gitenberg-dev/Second-Folio#11]
https://www.flowdock.com/app/gluejar/gitenberg/threads/-rug4IfclHP-riGPYcT4G5y4NeU

What about the books on RTC's side that we don't have on our spreadsheet as yes on RTC Cover?  Are we not doing u'Bleak House',
u'Great Expectations',
u'Persuasion',
u'The Good Soldier',
u'Ulysses'}?  Note that I think these books are on a list of 50 sent out earlier: https://www.flowdock.com/app/gluejar/gitenberg/messages/58683

**Comment by jenny8lee** [comment]
If there are covers that we need because they are done.

We have a good cover for Ulysses (black and white cobblestone)
And we have Persuasion and Great Expectations, but I don't love them.
What do we want to do?

**Comment by sethwoodworth** [comment]
We have a list of 50.  Lets push these books into the next set of books we release.  I also assume more covers will arrive next month from artists?

**Comment by jenny8lee** [comment]
Yes. More covers are supposed to arrive.
