### ISSUE TITLE
Regenerate all yaml files

### ISSUE THREAD

**Issue by sethwoodworth** [gitenberg-dev/Second-Folio#14]
- rerun cover add code

**Comment by rdhyee** [comment]
I've now updated all yaml files with YAML from [bookinfo5.sql](https://www.flowdock.com/app/gluejar/gitenberg/threads/k3wjjFzkfqWclOZVGjIgXumMmW0).  See, for example, https://github.com/GITenberg/My-Antonia_242/commit/61e6f396145121e9ec863be86d839e0212bd8db8

**Comment by rdhyee** [comment]
Now to update publisher field to RTC.

**Comment by rdhyee** [comment]
@sethwoodworth:  should I write 

```
_version: 0.0.1
```

to all the metadata.yaml that don't already have `_version`?

**Comment by rdhyee** [comment]
An example change: https://github.com/GITenberg/Don-Quixote_996/commit/4f198705f3c035951e24c7beaf8ce77c3ae4c9eb

I think I'll just do all the repos...easy enough to undo.

**Comment by rdhyee** [comment]
@sethwoodworth I think issue is done.

**Comment by eshellman** [comment]
how will the version string get updated on new tags?

**Comment by rdhyee** [comment]
Good question about how version gets updated.  I've been doing it manually on https://github.com/GITenberg/Adventures-of-Huckleberry-Finn_76/blob/master/metadata.yaml.  I think @sethwoodworth is working on some code in `gitberg` to sync up the tag and `_version` in metadata.yaml.

**Comment by sethwoodworth** [comment]
Yes, as Raymond describes, gitberg will handle this.

gitenberg-dev/gitberg/issues/1 <-- where this is tracked.  We can close this issue.
