### ISSUE TITLE
Books need metadata.yaml files

### ISSUE THREAD

**Issue by sethwoodworth** [gitenberg-dev/Second-Folio#7]
- [x] Decide if we call it `metadata.yml` or `metadata.yaml` -- check wikipedia
- [x] commit to each repo (See: gitenberg-dev/gitberg#7)

**Comment by sethwoodworth** [comment]
Add repo as _repo

**Comment by rdhyee** [comment]
Eric uploaded a .sql file for metadata: https://www.flowdock.com/app/gluejar/gitenberg/threads/qXafFRV5K4WM0sVN6Qp16s0qt20

**Comment by rdhyee** [comment]
@eshellman :  any reason why we shouldn't write your metadata.yaml files to the 50 Second Folio repos?

**Comment by eshellman** [comment]
no, but fixes are still flowing, hold off on writing 43,000

**Comment by rdhyee** [comment]
I'm going to close this issue because we've been working with the metadata.yaml for the Second Folio repos.
